import os


    
''' Environment Directory Config '''
_STATIC_FILE_NAME="Site_Master_Extract.xlsx"
_RAW_SCORES_DIRECTORY='Raw_Scores'
_CLEANED_SCORES_DIRECTORY='Cleaned_Scores'
_MASTER_DATA_DIRECTORY='Master_Data'
_STAGING_AREA_DIRECTORY=os.path.join(_MASTER_DATA_DIRECTORY, 'Recursive_Staging_Area')

# _STATIC_QUERY="SELECT SITE_INFO_ID SR_NUM, SOURCE_IDENTIFIER, DATA_SOURCE_NAME, PROTOCOL_NUMBER, SITE_NUMBER SITE_NUM, UNIQUE_SITE_ID, COUNTRY,SITE_NAME, SITE_STATESTATE, SITE_CITY CITY, SITE_ADDRESS_LINE_1 ADDRESS_LINE_1, SITE_ADDRESS_LINE_2 ADDRESS_LINE_2, SITE_ADDRESS_LINE_3 ADDRESS_LINE_3, SITE_ZIP_CODE POSTAL_CODE, NULL SITE_STATUS FROM RnD_MART.DM_SITE_INFORMATION WHERE (SITE_STATE+SITE_CITY+SITE_ADDRESS_LINE_1+SITE_ZIP_CODE) IS NOT NULL ORDER BY SITE_ZIP_CODE, SITE_NAME, SITE_STATE, SITE_CITY, (SITE_STATE+SITE_CITY+SITE_ADDRESS_LINE_1+SITE_ZIP_CODE);"
# _SQL_SERVER_CONN=pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};'+'SERVER=takdev-rnd.rda.onetakeda.com;'+'DATABASE=RnD_DB;'+'UID=Rnd_ETL;'+'PWD=rndetl@2017', charset='utf8')



''' Data_Fields Config '''
_FIELDS_TO_CONCAT={ 'CONCAT_ADDRESS':   ['ADDRESS_LINE_1','ADDRESS_LINE_2','ADDRESS_LINE_3'] }
_COLUMNS_TO_CLEAN=['ADDRESS_LINE_1','ADDRESS_LINE_2','ADDRESS_LINE_3','SITE_NAME','STATE','CITY','POSTAL_CODE']
_MAXSIZE=500



''' R_Code Config '''
_RSCRIPT_CMD="C:/Program Files/R/R-3.4.4/bin/i386/Rscript"
#_RSCRIPT_CMD="Rscript"
_SCRIPT_NAME="Site_Master_Record_Linkage.R"
_DEDUP_METHOD='Dedup'
_LINKAGE_METHOD='Linkage'



''' Match_Score_Computation '''
_BINARIES_NAME="levenshtein"
_BINARIES_EXTENSION=".dll"
#_BINARIES_EXTENSION=".so"
_THRESHOLD_FOR_INDIVIDUAL=0.85
_THRESHOLD_FOR_ADDRESS_COMBINED=0.75

_THRESHOLDS_DICT={
'CONCAT_ADDRESS': _THRESHOLD_FOR_ADDRESS_COMBINED,
'SITE_NAME': _THRESHOLD_FOR_INDIVIDUAL,
'STATE': _THRESHOLD_FOR_INDIVIDUAL,
'CITY': _THRESHOLD_FOR_INDIVIDUAL,
'POSTAL_CODE': _THRESHOLD_FOR_INDIVIDUAL
}

_COLS_FOR_TOTAL_MATCH_CALC=[colname+'_COMPARISON_SCORE' for colname in _THRESHOLDS_DICT]
_SCALING_FACTOR=3
_TOTAL_MATCHES_THRESHOLD=4